// Code generated by muxt. DO NOT EDIT.

package hypertext

import (
	"bytes"
	"context"
	"net/http"
)

type serverInterface interface {
	Index(_ context.Context) IndexData
}

func routes(mux *http.ServeMux, receiver serverInterface) {
	mux.HandleFunc("GET /about", func(response http.ResponseWriter, request *http.Request) {
		execute(response, request, true, "GET /about", http.StatusOK, request)
	})
	mux.HandleFunc("GET /{$}", func(response http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		data := receiver.Index(ctx)
		execute(response, request, true, "GET /{$} Index(ctx)", http.StatusOK, data)
	})
}
func execute(response http.ResponseWriter, request *http.Request, writeHeader bool, name string, code int, data any) {
	buf := bytes.NewBuffer(nil)
	if err := templates.ExecuteTemplate(buf, name, data); err != nil {
		http.Error(response, err.Error(), http.StatusInternalServerError)
		return
	}
	if writeHeader {
		response.Header().Set("content-type", "text/html; charset=utf-8")
		response.WriteHeader(code)
	}
	_, _ = buf.WriteTo(response)
}
