// Code generated by muxt. DO NOT EDIT.
// muxt version: (devel)

package hypertext

import (
	"bytes"
	"cmp"
	"context"
	"errors"
	"io"
	"log/slog"
	"net/http"
	"path"
	"strconv"
)

type RoutesReceiver interface {
	SubmitFormEditRow(fruitID int, form EditRow) EditRowPage
	GetFormEditRow(fruitID int) EditRowPage
	List(_ context.Context) []Row
}

func TemplateRoutes(mux *http.ServeMux, receiver RoutesReceiver) {
	mux.HandleFunc("PATCH /fruits/{id}", func(response http.ResponseWriter, request *http.Request) {
		idParsed, err := strconv.Atoi(request.PathValue("id"))
		if err != nil {
			writeResponseHeaderStatusCodeAndBody(response, request, func(w io.Writer) (int, error) {
				var zv EditRowPage
				rd := newTemplateData(receiver, response, request, zv, false, err)
				err := templates.ExecuteTemplate(w, "PATCH /fruits/{id} SubmitFormEditRow(id, form)", rd)
				sc := cmp.Or(rd.statusCode, http.StatusBadRequest)
				return sc, err
			})
			return
		}
		id := idParsed
		request.ParseForm()
		var form EditRow
		{
			value, err := strconv.Atoi(request.FormValue("count"))
			if err != nil {
				writeResponseHeaderStatusCodeAndBody(response, request, func(w io.Writer) (int, error) {
					var zv EditRowPage
					rd := newTemplateData(receiver, response, request, zv, false, err)
					err := templates.ExecuteTemplate(w, "PATCH /fruits/{id} SubmitFormEditRow(id, form)", rd)
					sc := cmp.Or(rd.statusCode, http.StatusBadRequest)
					return sc, err
				})
				return
			}
			if value < 0 {
				writeResponseHeaderStatusCodeAndBody(response, request, func(w io.Writer) (int, error) {
					var zv EditRowPage
					rd := newTemplateData(receiver, response, request, zv, false, errors.New("count must not be less than 0"))
					err := templates.ExecuteTemplate(w, "PATCH /fruits/{id} SubmitFormEditRow(id, form)", rd)
					sc := cmp.Or(rd.statusCode, http.StatusBadRequest)
					return sc, err
				})
				return
			}
			form.Value = value
		}
		result := receiver.SubmitFormEditRow(id, form)
		writeResponseHeaderStatusCodeAndBody(response, request, func(w io.Writer) (int, error) {
			rd := newTemplateData(receiver, response, request, result, true, nil)
			err := templates.ExecuteTemplate(w, "PATCH /fruits/{id} SubmitFormEditRow(id, form)", rd)
			sc := cmp.Or(rd.statusCode, http.StatusOK)
			return sc, err
		})
	})
	mux.HandleFunc("GET /fruits/{id}/edit", func(response http.ResponseWriter, request *http.Request) {
		idParsed, err := strconv.Atoi(request.PathValue("id"))
		if err != nil {
			writeResponseHeaderStatusCodeAndBody(response, request, func(w io.Writer) (int, error) {
				var zv EditRowPage
				rd := newTemplateData(receiver, response, request, zv, false, err)
				err := templates.ExecuteTemplate(w, "GET /fruits/{id}/edit GetFormEditRow(id)", rd)
				sc := cmp.Or(rd.statusCode, http.StatusBadRequest)
				return sc, err
			})
			return
		}
		id := idParsed
		result := receiver.GetFormEditRow(id)
		writeResponseHeaderStatusCodeAndBody(response, request, func(w io.Writer) (int, error) {
			rd := newTemplateData(receiver, response, request, result, true, nil)
			err := templates.ExecuteTemplate(w, "GET /fruits/{id}/edit GetFormEditRow(id)", rd)
			sc := cmp.Or(rd.statusCode, http.StatusOK)
			return sc, err
		})
	})
	mux.HandleFunc("GET /help", func(response http.ResponseWriter, request *http.Request) {
		var result = struct {
		}{}
		writeResponseHeaderStatusCodeAndBody(response, request, func(w io.Writer) (int, error) {
			rd := newTemplateData(receiver, response, request, result, true, nil)
			err := templates.ExecuteTemplate(w, "GET /help", rd)
			sc := cmp.Or(rd.statusCode, http.StatusOK)
			return sc, err
		})
	})
	mux.HandleFunc("GET /{$}", func(response http.ResponseWriter, request *http.Request) {
		ctx := request.Context()
		result := receiver.List(ctx)
		writeResponseHeaderStatusCodeAndBody(response, request, func(w io.Writer) (int, error) {
			rd := newTemplateData(receiver, response, request, result, true, nil)
			err := templates.ExecuteTemplate(w, "GET /{$} List(ctx)", rd)
			sc := cmp.Or(rd.statusCode, http.StatusOK)
			return sc, err
		})
	})
}

func writeResponseHeaderStatusCodeAndBody(response http.ResponseWriter, request *http.Request, execute func(io.Writer) (int, error)) {
	buf := bytes.NewBuffer(nil)
	statusCode, err := execute(buf)
	if err != nil {
		slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
		http.Error(response, "failed to render page", http.StatusInternalServerError)
		return
	}
	if contentType := response.Header().Get("content-type"); contentType == "" {
		response.Header().Set("content-type", "text/html; charset=utf-8")
	}
	response.Header().Set("content-length", strconv.Itoa(buf.Len()))
	response.WriteHeader(statusCode)
	_, _ = buf.WriteTo(response)
}

func writeResponseBody(response http.ResponseWriter, request *http.Request, execute func(io.Writer) error) {
	buf := bytes.NewBuffer(nil)
	err := execute(buf)
	if err != nil {
		slog.ErrorContext(request.Context(), "failed to render page", slog.String("path", request.URL.Path), slog.String("pattern", request.Pattern), slog.String("error", err.Error()))
		http.Error(response, "failed to render page", http.StatusInternalServerError)
		return
	}
	_, _ = buf.WriteTo(response)
}

type TemplateData[T any] struct {
	receiver   RoutesReceiver
	response   http.ResponseWriter
	request    *http.Request
	result     T
	statusCode int
	okay       bool
	err        error
}

func newTemplateData[T any](receiver RoutesReceiver, response http.ResponseWriter, request *http.Request, result T, okay bool, err error) *TemplateData[T] {
	return &TemplateData[T]{receiver: receiver, response: response, request: request, result: result, okay: okay, err: err}
}

func ChangeTemplateDataResult[NewResultType, PrevResultType any](td *TemplateData[PrevResultType], result NewResultType, okay bool, err error) *TemplateData[NewResultType] {
	return &TemplateData[NewResultType]{receiver: td.receiver, response: td.response, request: td.request, statusCode: 0, result: result, okay: okay, err: err}
}

func (data *TemplateData[T]) Path() TemplateRoutePaths {
	return TemplateRoutePaths{}
}

func (data *TemplateData[T]) Result() T {
	return data.result
}

func (data *TemplateData[T]) Request() *http.Request {
	return data.request
}

func (data *TemplateData[T]) StatusCode(statusCode int) *TemplateData[T] {
	data.statusCode = statusCode
	return data
}

func (data *TemplateData[T]) Header(key, value string) *TemplateData[T] {
	data.response.Header().Set(key, value)
	return data
}

func (data *TemplateData[T]) Ok() bool {
	return data.okay
}

func (data *TemplateData[T]) Err() error {
	return data.err
}

func (data *TemplateData[T]) Receiver() RoutesReceiver {
	return data.receiver
}

type TemplateRoutePaths struct {
}

func TemplateRoutePath() TemplateRoutePaths {
	return TemplateRoutePaths{}
}

func (TemplateRoutePaths) SubmitFormEditRow(id int) string {
	return "/" + path.Join("fruits", strconv.Itoa(id))
}

func (TemplateRoutePaths) GetFormEditRow(id int) string {
	return "/" + path.Join("fruits", strconv.Itoa(id), "edit")
}

func (TemplateRoutePaths) ReadHelp() string {
	return "/help"
}

func (TemplateRoutePaths) List() string {
	return "/"
}
