package main

import (
	"bytes"
	"io"
	"log"
	"os"
	"path/filepath"

	"github.com/crhntr/muxt"
	"github.com/crhntr/muxt/internal/configuration"
)

const CodeGenerationComment = "// Code generated by muxt. DO NOT EDIT."

func generateCommand(args []string, workingDirectory string, getEnv func(string) string, stdout, stderr io.Writer) error {
	g, err := configuration.NewGenerate(args, getEnv, stderr)
	if err != nil {
		return err
	}
	s, err := muxt.TemplateRoutesFile(workingDirectory, log.New(stdout, "", 0), muxt.RoutesFileConfiguration{
		Package:           getEnv("GOPACKAGE"),
		TemplatesVar:      g.TemplatesVariable,
		RoutesFunc:        g.RoutesFunction,
		ReceiverType:      g.ReceiverIdent,
		ReceiverInterface: g.ReceiverInterfaceIdent,
		Output:            g.OutputFilename,
	})
	if err != nil {
		return err
	}
	var sb bytes.Buffer
	writeCodeGenerationComment(&sb)
	sb.WriteString(s)
	return os.WriteFile(filepath.Join(workingDirectory, g.OutputFilename), sb.Bytes(), 0o644)
}

func writeCodeGenerationComment(w io.StringWriter) {
	_, _ = w.WriteString(CodeGenerationComment)
	if v, ok := cliVersion(); ok {
		_, _ = w.WriteString("\n// muxt version: ")
		_, _ = w.WriteString(v)
		_, _ = w.WriteString("\n\n")
	}
}
